#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR
PIDF="processid"
start () {
    if [ -f $PIDF ]; then
        echo "Already running"
    else
        /home/nexus/node/bin/node stockalertbot.js > log 2>&1 &
        echo $! > $PIDF
    fi
}
stop () {
    if [ -f processid ]; then
        kill $(<"$PIDF")
        rm $PIDF
    else
        echo "Already stopped"
    fi
}
if [ "$1" == "start" ]; then
    start
elif [ "$1" == "stop" ]; then
    stop
elif [ "$1" == "restart" ]; then
    stop
    start
fi
